# Generated by Django 4.0.3 on 2022-03-14 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaryDoctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('freeHour', models.BooleanField(default=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='diaryDoctor.diarydoctor')),
            ],
        ),
    ]
