# Generated by Django 4.0.3 on 2022-03-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryPatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querypatient',
            name='daySchedule',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
