# Generated by Django 4.0.3 on 2022-03-18 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queryPatient', '0002_alter_querypatient_dayschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querypatient',
            name='daySchedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
